name: Crawl upon new requests

on:
  issues:
    types: [opened]

jobs:
  crawl-and-commit:
    if: github.event.issue.author_association == 'OWNER' || github.event.issue.author_association == 'MEMBER'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Crawler
        run: |
          python3 storemap.py

      - name: Commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add ./json/
          git commit -m "Auto update  $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes?"
          git push

